[WIP] Docs/networks/lukso tool.md
lukso-network/docs-website pull request #11
Opened 2021-08-25 14:33 UTC by patred20

2021-09-13 16:31 UTC, frozeman approved these changes

2021-09-14 07:06 UTC, mxmar commented
@patred20 Is this still `WIP` (`Draft`) PR?

2021-09-14 07:20 UTC, mxmar requested changes
Missing information with example how exactly run `lukso` binary after installer finished its work.

1. Description step-by-step
2. Example

2021-09-14 09:13 UTC, frozeman commented on docs/networks/lukso-tool.md
> +# Lukso setup/cli tool
LUKSO

2021-09-14 09:13 UTC, frozeman commented on docs/networks/lukso-tool.md
> +# Lukso setup/cli tool
LUKSO CLI

2021-09-14 09:15 UTC, frozeman commented
lukso-cli.md

2021-09-14 09:21 UTC, frozeman commented on docs/networks/lukso-tool.md
> +## Config file
`## Example config file`

2021-09-30 10:31 UTC, frozeman approved these changes

2021-09-30 10:32 UTC, frozeman approved these changes
good

2021-09-30 10:32 UTC, merged